## <center> Avito Cars - Data Engineering <center>

In [7]:
pip install scikit_learn

Collecting scikit_learn
  Downloading scikit_learn-1.5.1-cp312-cp312-win_amd64.whl.metadata (12 kB)
Requirement already satisfied: numpy>=1.19.5 in c:\users\hp\appdata\local\programs\python\python312\lib\site-packages (from scikit_learn) (1.26.4)
Requirement already satisfied: scipy>=1.6.0 in c:\users\hp\appdata\local\programs\python\python312\lib\site-packages (from scikit_learn) (1.14.0)
Collecting joblib>=1.2.0 (from scikit_learn)
  Downloading joblib-1.4.2-py3-none-any.whl.metadata (5.4 kB)
Collecting threadpoolctl>=3.1.0 (from scikit_learn)
  Downloading threadpoolctl-3.5.0-py3-none-any.whl.metadata (13 kB)
Downloading scikit_learn-1.5.1-cp312-cp312-win_amd64.whl (10.9 MB)
   ---------------------------------------- 0.0/10.9 MB ? eta -:--:--
   ---------------------------------------- 0.0/10.9 MB ? eta -:--:--
   ---------------------------------------- 0.0/10.9 MB 281.8 kB/s eta 0:00:39
   ---------------------------------------- 0.1/10.9 MB 299.4 kB/s eta 0:00:37
   ---------------------------------------- 0.1/10.9 MB 450.6 kB/s eta 0:00:25
   ---------------------------------------- 0.1/10.9 MB 415.1 kB/s eta 0:00:27
    --------------------------------------- 0.2/10.9 MB 468.3 kB/s eta 0:00:24
    --------------------------------------- 0.2/10.9 MB 468.3 kB/s eta 0:00:24
    --------------------------------------- 0.2/10.9 MB 468.3 kB/s eta 0:00:24
    --------------------------------------- 0.2/10.9 MB 471.0 kB/s eta 0:00:23
    --------------------------------------- 0.2/10.9 MB 471.0 kB/s eta 0:00:23
   - -------------------------------------- 0.3/10.9 MB 442.4 kB/s eta 0:00:25
   - -------------------------------------- 0.3/10.9 MB 437.1 kB/s eta 0:00:25
   - -------------------------------------- 0.3/10.9 MB 447.2 kB/s eta 0:00:24
   - -------------------------------------- 0.3/10.9 MB 450.6 kB/s eta 0:00:24
   - -------------------------------------- 0.4/10.9 MB 458.9 kB/s eta 0:00:24
   - -------------------------------------- 0.4/10.9 MB 461.6 kB/s eta 0:00:23
   - -------------------------------------- 0.4/10.9 MB 448.7 kB/s eta 0:00:24
   - -------------------------------------- 0.4/10.9 MB 448.1 kB/s eta 0:00:24
   - -------------------------------------- 0.5/10.9 MB 450.6 kB/s eta 0:00:24
   - -------------------------------------- 0.5/10.9 MB 450.3 kB/s eta 0:00:24
   - -------------------------------------- 0.5/10.9 MB 450.3 kB/s eta 0:00:24
   - -------------------------------------- 0.5/10.9 MB 416.3 kB/s eta 0:00:26
   - -------------------------------------- 0.5/10.9 MB 412.0 kB/s eta 0:00:26
   - -------------------------------------- 0.5/10.9 MB 423.2 kB/s eta 0:00:25
   - -------------------------------------- 0.5/10.9 MB 423.2 kB/s eta 0:00:25
   -- ------------------------------------- 0.6/10.9 MB 417.0 kB/s eta 0:00:25
   -- ------------------------------------- 0.6/10.9 MB 429.7 kB/s eta 0:00:25
   -- ------------------------------------- 0.6/10.9 MB 420.9 kB/s eta 0:00:25
   -- ------------------------------------- 0.7/10.9 MB 421.4 kB/s eta 0:00:25
   -- ------------------------------------- 0.7/10.9 MB 426.1 kB/s eta 0:00:25
   -- ------------------------------------- 0.7/10.9 MB 430.7 kB/s eta 0:00:24
   -- ------------------------------------- 0.7/10.9 MB 424.9 kB/s eta 0:00:25
   -- ------------------------------------- 0.7/10.9 MB 423.2 kB/s eta 0:00:25
   -- ------------------------------------- 0.8/10.9 MB 423.5 kB/s eta 0:00:25
   -- ------------------------------------- 0.8/10.9 MB 423.8 kB/s eta 0:00:24
   -- ------------------------------------- 0.8/10.9 MB 411.8 kB/s eta 0:00:25
   -- ------------------------------------- 0.8/10.9 MB 411.8 kB/s eta 0:00:25
   -- ------------------------------------- 0.8/10.9 MB 411.8 kB/s eta 0:00:25
   --- ------------------------------------ 0.9/10.9 MB 413.9 kB/s eta 0:00:25
   --- ------------------------------------ 0.9/10.9 MB 413.9 kB/s eta 0:00:25
   --- ------------------------------------ 0.9/10.9 MB 413.9 kB/s eta 0:00:25
   --- ------------------------------------ 0.9/10.9 MB 413.9 kB/s eta 0:00:25
   --- ------------------------------------ 0.9/10.9 MB 413.9 kB/s eta 0:00:25
   --- ------------------------------------ 0.9/10.9 MB 413.9 kB/s eta 0:00:25
   --- ------------------------------------ 0.9/10.9 MB 377.7 kB/s eta 0:00:27
   --- ------------------------------------ 0.9/10.9 MB 381.3 kB/s eta 0:00:27
   --- ------------------------------------ 1.0/10.9 MB 381.7 kB/s eta 0:00:27
   --- ------------------------------------ 1.0/10.9 MB 385.0 kB/s eta 0:00:26
   --- ------------------------------------ 1.0/10.9 MB 385.0 kB/s eta 0:00:26
   --- ------------------------------------ 1.0/10.9 MB 385.0 kB/s eta 0:00:26
   --- ------------------------------------ 1.0/10.9 MB 385.0 kB/s eta 0:00:26
   --- ------------------------------------ 1.1/10.9 MB 391.0 kB/s eta 0:00:26
   --- ------------------------------------ 1.1/10.9 MB 391.0 kB/s eta 0:00:26
   ---- ----------------------------------- 1.1/10.9 MB 385.4 kB/s eta 0:00:26
   ---- ----------------------------------- 1.1/10.9 MB 384.7 kB/s eta 0:00:26
   ---- ----------------------------------- 1.1/10.9 MB 384.9 kB/s eta 0:00:26
   ---- ----------------------------------- 1.2/10.9 MB 391.9 kB/s eta 0:00:25
   ---- ----------------------------------- 1.2/10.9 MB 389.9 kB/s eta 0:00:25
   ---- ----------------------------------- 1.3/10.9 MB 395.2 kB/s eta 0:00:25
   ---- ----------------------------------- 1.3/10.9 MB 392.6 kB/s eta 0:00:25
   ---- ----------------------------------- 1.3/10.9 MB 392.6 kB/s eta 0:00:25
   ---- ----------------------------------- 1.3/10.9 MB 384.1 kB/s eta 0:00:26
   ---- ----------------------------------- 1.4/10.9 MB 398.7 kB/s eta 0:00:25
   ----- ---------------------------------- 1.4/10.9 MB 401.1 kB/s eta 0:00:24
   ----- ---------------------------------- 1.4/10.9 MB 401.1 kB/s eta 0:00:24
   ----- ---------------------------------- 1.4/10.9 MB 404.3 kB/s eta 0:00:24
   ----- ---------------------------------- 1.5/10.9 MB 406.4 kB/s eta 0:00:24
   ----- ---------------------------------- 1.5/10.9 MB 403.9 kB/s eta 0:00:24
   ----- ---------------------------------- 1.5/10.9 MB 408.3 kB/s eta 0:00:24
   ----- ---------------------------------- 1.5/10.9 MB 409.6 kB/s eta 0:00:23
   ----- ---------------------------------- 1.6/10.9 MB 409.3 kB/s eta 0:00:23
   ----- ---------------------------------- 1.6/10.9 MB 413.0 kB/s eta 0:00:23
   ----- ---------------------------------- 1.6/10.9 MB 409.0 kB/s eta 0:00:23
   ----- ---------------------------------- 1.6/10.9 MB 409.0 kB/s eta 0:00:23
   ----- ---------------------------------- 1.6/10.9 MB 403.0 kB/s eta 0:00:24
   ----- ---------------------------------- 1.6/10.9 MB 397.8 kB/s eta 0:00:24
   ----- ---------------------------------- 1.6/10.9 MB 397.8 kB/s eta 0:00:24
   ----- ---------------------------------- 1.6/10.9 MB 397.8 kB/s eta 0:00:24
   ------ --------------------------------- 1.7/10.9 MB 399.5 kB/s eta 0:00:24
   ------ --------------------------------- 1.7/10.9 MB 401.3 kB/s eta 0:00:23
   ------ --------------------------------- 1.7/10.9 MB 401.3 kB/s eta 0:00:23
   ------ --------------------------------- 1.8/10.9 MB 397.4 kB/s eta 0:00:24
   ------ --------------------------------- 1.8/10.9 MB 397.4 kB/s eta 0:00:24
   ------ --------------------------------- 1.8/10.9 MB 397.4 kB/s eta 0:00:24
   ------ --------------------------------- 1.8/10.9 MB 397.4 kB/s eta 0:00:24
   ------ --------------------------------- 1.8/10.9 MB 397.4 kB/s eta 0:00:24
   ------ --------------------------------- 1.8/10.9 MB 397.4 kB/s eta 0:00:24
   ------ --------------------------------- 1.8/10.9 MB 397.4 kB/s eta 0:00:24
   ------ --------------------------------- 1.8/10.9 MB 397.4 kB/s eta 0:00:24
   ------ --------------------------------- 1.9/10.9 MB 377.5 kB/s eta 0:00:25
   ------ --------------------------------- 1.9/10.9 MB 378.3 kB/s eta 0:00:24
   ------ --------------------------------- 1.9/10.9 MB 378.3 kB/s eta 0:00:24
   ------ --------------------------------- 1.9/10.9 MB 374.2 kB/s eta 0:00:25
   ------- -------------------------------- 1.9/10.9 MB 374.8 kB/s eta 0:00:25
   ------- -------------------------------- 1.9/10.9 MB 372.3 kB/s eta 0:00:25
   ------- -------------------------------- 2.0/10.9 MB 372.9 kB/s eta 0:00:25
   ------- -------------------------------- 2.0/10.9 MB 371.5 kB/s eta 0:00:25
   ------- -------------------------------- 2.0/10.9 MB 374.8 kB/s eta 0:00:24
   ------- -------------------------------- 2.0/10.9 MB 376.2 kB/s eta 0:00:24
   ------- -------------------------------- 2.0/10.9 MB 375.9 kB/s eta 0:00:24
   ------- -------------------------------- 2.0/10.9 MB 375.9 kB/s eta 0:00:24
   ------- -------------------------------- 2.1/10.9 MB 371.9 kB/s eta 0:00:24
   ------- -------------------------------- 2.1/10.9 MB 371.7 kB/s eta 0:00:24
   ------- -------------------------------- 2.1/10.9 MB 371.7 kB/s eta 0:00:24
   ------- -------------------------------- 2.1/10.9 MB 371.7 kB/s eta 0:00:24
   ------- -------------------------------- 2.1/10.9 MB 366.1 kB/s eta 0:00:25
   ------- -------------------------------- 2.1/10.9 MB 367.5 kB/s eta 0:00:24
   ------- -------------------------------- 2.2/10.9 MB 369.0 kB/s eta 0:00:24
   -------- ------------------------------- 2.2/10.9 MB 370.3 kB/s eta 0:00:24
   -------- ------------------------------- 2.2/10.9 MB 371.6 kB/s eta 0:00:24
   -------- ------------------------------- 2.2/10.9 MB 371.6 kB/s eta 0:00:24
   -------- ------------------------------- 2.2/10.9 MB 368.2 kB/s eta 0:00:24
   -------- ------------------------------- 2.2/10.9 MB 368.2 kB/s eta 0:00:24
   -------- ------------------------------- 2.3/10.9 MB 365.2 kB/s eta 0:00:24
   -------- ------------------------------- 2.3/10.9 MB 365.6 kB/s eta 0:00:24
   -------- ------------------------------- 2.3/10.9 MB 366.1 kB/s eta 0:00:24
   -------- ------------------------------- 2.3/10.9 MB 367.6 kB/s eta 0:00:24
   -------- ------------------------------- 2.3/10.9 MB 367.6 kB/s eta 0:00:24
   -------- ------------------------------- 2.4/10.9 MB 367.5 kB/s eta 0:00:24
   -------- ------------------------------- 2.4/10.9 MB 367.5 kB/s eta 0:00:24
   -------- ------------------------------- 2.4/10.9 MB 367.5 kB/s eta 0:00:24
   -------- ------------------------------- 2.4/10.9 MB 362.6 kB/s eta 0:00:24
   -------- ------------------------------- 2.4/10.9 MB 363.2 kB/s eta 0:00:24
   -------- ------------------------------- 2.5/10.9 MB 365.1 kB/s eta 0:00:24
   -------- ------------------------------- 2.5/10.9 MB 365.1 kB/s eta 0:00:24
   -------- ------------------------------- 2.5/10.9 MB 365.1 kB/s eta 0:00:24
   --------- ------------------------------ 2.5/10.9 MB 359.1 kB/s eta 0:00:24
   --------- ------------------------------ 2.5/10.9 MB 360.4 kB/s eta 0:00:24
   --------- ------------------------------ 2.5/10.9 MB 360.4 kB/s eta 0:00:24
   --------- ------------------------------ 2.5/10.9 MB 360.4 kB/s eta 0:00:24
   --------- ------------------------------ 2.5/10.9 MB 360.4 kB/s eta 0:00:24
   --------- ------------------------------ 2.6/10.9 MB 360.1 kB/s eta 0:00:24
   --------- ------------------------------ 2.6/10.9 MB 360.0 kB/s eta 0:00:24
   --------- ------------------------------ 2.6/10.9 MB 360.0 kB/s eta 0:00:24
   --------- ------------------------------ 2.6/10.9 MB 359.4 kB/s eta 0:00:24
   --------- ------------------------------ 2.6/10.9 MB 359.4 kB/s eta 0:00:24
   --------- ------------------------------ 2.6/10.9 MB 359.4 kB/s eta 0:00:24
   --------- ------------------------------ 2.6/10.9 MB 359.4 kB/s eta 0:00:24
   --------- ------------------------------ 2.6/10.9 MB 359.4 kB/s eta 0:00:24
   --------- ------------------------------ 2.6/10.9 MB 349.5 kB/s eta 0:00:24
   --------- ------------------------------ 2.6/10.9 MB 349.5 kB/s eta 0:00:24
   --------- ------------------------------ 2.6/10.9 MB 349.5 kB/s eta 0:00:24
   --------- ------------------------------ 2.6/10.9 MB 349.5 kB/s eta 0:00:24
   --------- ------------------------------ 2.7/10.9 MB 344.9 kB/s eta 0:00:24
   --------- ------------------------------ 2.7/10.9 MB 345.4 kB/s eta 0:00:24
   --------- ------------------------------ 2.7/10.9 MB 345.3 kB/s eta 0:00:24
   --------- ------------------------------ 2.7/10.9 MB 345.3 kB/s eta 0:00:24
   ---------- ----------------------------- 2.7/10.9 MB 344.5 kB/s eta 0:00:24
   ---------- ----------------------------- 2.7/10.9 MB 344.5 kB/s eta 0:00:24
   ---------- ----------------------------- 2.7/10.9 MB 344.5 kB/s eta 0:00:24
   ---------- ----------------------------- 2.8/10.9 MB 342.4 kB/s eta 0:00:24
   ---------- ----------------------------- 2.8/10.9 MB 342.4 kB/s eta 0:00:24
   ---------- ----------------------------- 2.8/10.9 MB 340.9 kB/s eta 0:00:24
   ---------- ----------------------------- 2.8/10.9 MB 339.5 kB/s eta 0:00:25
   ---------- ----------------------------- 2.8/10.9 MB 340.1 kB/s eta 0:00:24
   ---------- ----------------------------- 2.8/10.9 MB 339.4 kB/s eta 0:00:24
   ---------- ----------------------------- 2.8/10.9 MB 340.0 kB/s eta 0:00:24
   ---------- ----------------------------- 2.8/10.9 MB 340.0 kB/s eta 0:00:24
   ---------- ----------------------------- 2.8/10.9 MB 340.0 kB/s eta 0:00:24
   ---------- ----------------------------- 2.8/10.9 MB 340.0 kB/s eta 0:00:24
   ---------- ----------------------------- 2.8/10.9 MB 340.0 kB/s eta 0:00:24
   ---------- ----------------------------- 2.8/10.9 MB 340.0 kB/s eta 0:00:24
   ---------- ----------------------------- 2.8/10.9 MB 340.0 kB/s eta 0:00:24
   ---------- ----------------------------- 2.8/10.9 MB 340.0 kB/s eta 0:00:24
   ---------- ----------------------------- 2.9/10.9 MB 329.5 kB/s eta 0:00:25
   ---------- ----------------------------- 2.9/10.9 MB 329.5 kB/s eta 0:00:25
   ---------- ----------------------------- 2.9/10.9 MB 329.5 kB/s eta 0:00:25
   ---------- ----------------------------- 2.9/10.9 MB 329.5 kB/s eta 0:00:25
   ---------- ----------------------------- 2.9/10.9 MB 329.5 kB/s eta 0:00:25
   ---------- ----------------------------- 3.0/10.9 MB 329.4 kB/s eta 0:00:25
   ---------- ----------------------------- 3.0/10.9 MB 329.4 kB/s eta 0:00:25
   ---------- ----------------------------- 3.0/10.9 MB 329.4 kB/s eta 0:00:25
   ---------- ----------------------------- 3.0/10.9 MB 329.4 kB/s eta 0:00:25
   ----------- ---------------------------- 3.1/10.9 MB 328.8 kB/s eta 0:00:24
   ----------- ---------------------------- 3.1/10.9 MB 328.8 kB/s eta 0:00:24
   ----------- ---------------------------- 3.1/10.9 MB 328.8 kB/s eta 0:00:24
   ----------- ---------------------------- 3.1/10.9 MB 324.4 kB/s eta 0:00:25
   ----------- ---------------------------- 3.1/10.9 MB 324.4 kB/s eta 0:00:25
   ----------- ---------------------------- 3.1/10.9 MB 324.4 kB/s eta 0:00:25
   ----------- ---------------------------- 3.1/10.9 MB 324.4 kB/s eta 0:00:25
   ----------- ---------------------------- 3.1/10.9 MB 320.8 kB/s eta 0:00:25
   ----------- ---------------------------- 3.1/10.9 MB 320.8 kB/s eta 0:00:25
   ----------- ---------------------------- 3.1/10.9 MB 320.8 kB/s eta 0:00:25
   ----------- ---------------------------- 3.1/10.9 MB 320.8 kB/s eta 0:00:25
   ----------- ---------------------------- 3.1/10.9 MB 320.8 kB/s eta 0:00:25
   ----------- ---------------------------- 3.1/10.9 MB 320.8 kB/s eta 0:00:25
   ----------- ---------------------------- 3.1/10.9 MB 320.8 kB/s eta 0:00:25
   ----------- ---------------------------- 3.1/10.9 MB 320.8 kB/s eta 0:00:25
   ----------- ---------------------------- 3.1/10.9 MB 308.9 kB/s eta 0:00:26
   ----------- ---------------------------- 3.1/10.9 MB 308.9 kB/s eta 0:00:26
   ----------- ---------------------------- 3.1/10.9 MB 308.9 kB/s eta 0:00:26
   ----------- ---------------------------- 3.1/10.9 MB 308.9 kB/s eta 0:00:26
   ----------- ---------------------------- 3.1/10.9 MB 308.9 kB/s eta 0:00:26
   ----------- ---------------------------- 3.1/10.9 MB 304.3 kB/s eta 0:00:26
   ----------- ---------------------------- 3.2/10.9 MB 303.5 kB/s eta 0:00:26
   ----------- ---------------------------- 3.2/10.9 MB 304.5 kB/s eta 0:00:26
   ----------- ---------------------------- 3.2/10.9 MB 305.1 kB/s eta 0:00:26
   ----------- ---------------------------- 3.2/10.9 MB 304.7 kB/s eta 0:00:26
   ----------- ---------------------------- 3.2/10.9 MB 304.7 kB/s eta 0:00:26
   ----------- ---------------------------- 3.2/10.9 MB 304.7 kB/s eta 0:00:26
   ----------- ---------------------------- 3.2/10.9 MB 301.3 kB/s eta 0:00:26
   ----------- ---------------------------- 3.2/10.9 MB 301.3 kB/s eta 0:00:26
   ----------- ---------------------------- 3.2/10.9 MB 301.3 kB/s eta 0:00:26
   ----------- ---------------------------- 3.2/10.9 MB 301.3 kB/s eta 0:00:26
   ----------- ---------------------------- 3.2/10.9 MB 297.0 kB/s eta 0:00:26
   ----------- ---------------------------- 3.3/10.9 MB 297.2 kB/s eta 0:00:26
   ----------- ---------------------------- 3.3/10.9 MB 297.8 kB/s eta 0:00:26
   ----------- ---------------------------- 3.3/10.9 MB 297.8 kB/s eta 0:00:26
   ------------ --------------------------- 3.3/10.9 MB 295.8 kB/s eta 0:00:26
   ------------ --------------------------- 3.3/10.9 MB 295.8 kB/s eta 0:00:26
   ------------ --------------------------- 3.3/10.9 MB 295.2 kB/s eta 0:00:26
   ------------ --------------------------- 3.3/10.9 MB 295.2 kB/s eta 0:00:26
   ------------ --------------------------- 3.3/10.9 MB 295.2 kB/s eta 0:00:26
   ------------ --------------------------- 3.3/10.9 MB 295.2 kB/s eta 0:00:26
   ------------ --------------------------- 3.3/10.9 MB 295.2 kB/s eta 0:00:26
   ------------ --------------------------- 3.4/10.9 MB 292.9 kB/s eta 0:00:26
   ------------ --------------------------- 3.4/10.9 MB 292.9 kB/s eta 0:00:26
   ------------ --------------------------- 3.4/10.9 MB 291.9 kB/s eta 0:00:26
   ------------ --------------------------- 3.4/10.9 MB 290.8 kB/s eta 0:00:26
   ------------ --------------------------- 3.4/10.9 MB 290.8 kB/s eta 0:00:26
   ------------ --------------------------- 3.4/10.9 MB 290.6 kB/s eta 0:00:26
   ------------ --------------------------- 3.4/10.9 MB 290.6 kB/s eta 0:00:26
   ------------ --------------------------- 3.4/10.9 MB 290.0 kB/s eta 0:00:26
   ------------ --------------------------- 3.5/10.9 MB 289.4 kB/s eta 0:00:26
   ------------ --------------------------- 3.5/10.9 MB 289.4 kB/s eta 0:00:26
   ------------ --------------------------- 3.5/10.9 MB 289.2 kB/s eta 0:00:26
   ------------ --------------------------- 3.5/10.9 MB 289.2 kB/s eta 0:00:26
   ------------ --------------------------- 3.5/10.9 MB 289.2 kB/s eta 0:00:26
   ------------ --------------------------- 3.5/10.9 MB 289.2 kB/s eta 0:00:26
   ------------ --------------------------- 3.5/10.9 MB 286.9 kB/s eta 0:00:26
   ------------ --------------------------- 3.5/10.9 MB 286.7 kB/s eta 0:00:26
   ------------ --------------------------- 3.5/10.9 MB 286.7 kB/s eta 0:00:26
   ------------ --------------------------- 3.5/10.9 MB 286.7 kB/s eta 0:00:26
   ------------ --------------------------- 3.5/10.9 MB 286.7 kB/s eta 0:00:26
   ------------ --------------------------- 3.5/10.9 MB 286.7 kB/s eta 0:00:26
   ------------ --------------------------- 3.5/10.9 MB 282.9 kB/s eta 0:00:27
   ------------ --------------------------- 3.5/10.9 MB 282.9 kB/s eta 0:00:27
   ------------ --------------------------- 3.6/10.9 MB 282.4 kB/s eta 0:00:27
   ------------- -------------------------- 3.6/10.9 MB 281.4 kB/s eta 0:00:27
   ------------- -------------------------- 3.6/10.9 MB 281.3 kB/s eta 0:00:27
   ------------- -------------------------- 3.6/10.9 MB 281.3 kB/s eta 0:00:27
   ------------- -------------------------- 3.6/10.9 MB 280.5 kB/s eta 0:00:27
   ------------- -------------------------- 3.6/10.9 MB 280.3 kB/s eta 0:00:27

[notice] A new release of pip is available: 24.1.1 -> 24.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [8]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import sklearn 
from sklearn.preprocessing import StandardScaler,LabelEncoder,OneHotEncoder,PolynomialFeatures
#from sklearn.linear_modele import LinearRegression
import seaborn as sns

#feature selection tools
from sklearn.feature_selection import f_regression
from sklearn.feature_selection import f_classif
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import mutual_info_regression
from sklearn.feature_selection import mutual_info_classif
from sklearn.feature_selection import chi2
pd.set_option("display.max_rows" , 25)
warnings.filterwarnings("ignore")

In [9]:
# import data
df = pd.read_csv(r"C:\Users\hp\avito_cars_clean_data.csv")
df

,Unnamed: 0,price,hp,gearbox,power,is_first_use,origine,make,model,age,mileage,num_general_state
0,0,140000,6,Manuelle,Diesel,0,WW au Maroc,Renault,megane_4,6.50,77499.5,10
1,1,105000,6,Manuelle,Diesel,0,WW au Maroc,Citroen,C4,9.50,224999.5,9
2,2,217000,8,Automatique,Diesel,0,WW au Maroc,Land Rover,Range Rover Evoque,7.50,114999.5,9
3,3,258000,8,Automatique,Diesel,1,WW au Maroc,BMW,Serie 4 gran coupé,7.50,144999.5,9
4,4,143000,8,Automatique,Diesel,0,WW au Maroc,Fiat,500X,8.50,124999.5,9
...,...,...,...,...,...,...,...,...,...,...,...,...
34794,35722,125000,6,Automatique,Essence,1,WW au Maroc,Kia,Picanto,3.50,32499.5,10
34795,35723,50000,7,Manuelle,Essence,1,Dédouanée,Renault,Clio,22.51,22499.5,8
34796,35724,120000,7,Manuelle,Diesel,1,WW au Maroc,Dacia,Duster,8.50,134999.5,8
34797,35725,85000,8,Manuelle,Diesel,1,Dédouanée,Volkswagen,GOLF 5,17.51,274999.5,8
34798,35726,30000,11,Manuelle,Essence,0,WW au Maroc,Peugeot,406,25.51,224999.5,8

In [14]:
dummies_data = pd.get_dummies(df,prefix="",prefix_sep="" ,columns=['gearbox','power','origine'], dtype="int")
dummies_data

,Unnamed: 0,price,hp,is_first_use,make,model,age,mileage,num_general_state,Automatique,Manuelle,Diesel,Electrique,Essence,Hybride,Dédouanée,Importée neuve,Pas encore dédouanée,WW au Maroc
0,0,140000,6,0,Renault,megane_4,6.50,77499.5,10,0,1,1,0,0,0,0,0,0,1
1,1,105000,6,0,Citroen,C4,9.50,224999.5,9,0,1,1,0,0,0,0,0,0,1
2,2,217000,8,0,Land Rover,Range Rover Evoque,7.50,114999.5,9,1,0,1,0,0,0,0,0,0,1
3,3,258000,8,1,BMW,Serie 4 gran coupé,7.50,144999.5,9,1,0,1,0,0,0,0,0,0,1
4,4,143000,8,0,Fiat,500X,8.50,124999.5,9,1,0,1,0,0,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34794,35722,125000,6,1,Kia,Picanto,3.50,32499.5,10,1,0,0,0,1,0,0,0,0,1
34795,35723,50000,7,1,Renault,Clio,22.51,22499.5,8,0,1,0,0,1,0,1,0,0,0
34796,35724,120000,7,1,Dacia,Duster,8.50,134999.5,8,0,1,1,0,0,0,0,0,0,1
34797,35725,85000,8,1,Volkswagen,GOLF 5,17.51,274999.5,8,0,1,1,0,0,0,1,0,0,0
34798,35726,30000,11,0,Peugeot,406,25.51,224999.5,8,0,1,0,0,1,0,0,0,0,1

In [22]:
#Apply label encoder on make and model 
le=LabelEncoder()
mark_model=df[["make","model"]]
#y=lambda x:le.fit_transform

encoded_df=mark_model.apply(le.fit_transform)
dummies_data[["make","model"]] = encoded_df
dummies_data

,Unnamed: 0,price,hp,is_first_use,make,model,age,mileage,num_general_state,Automatique,Manuelle,Diesel,Electrique,Essence,Hybride,Dédouanée,Importée neuve,Pas encore dédouanée,WW au Maroc
0,0,140000,6,0,46,657,6.50,77499.5,10,0,1,1,0,0,0,0,0,0,1
1,1,105000,6,0,13,158,9.50,224999.5,9,0,1,1,0,0,0,0,0,0,1
2,2,217000,8,0,35,457,7.50,114999.5,9,1,0,1,0,0,0,0,0,0,1
3,3,258000,8,1,5,508,7.50,144999.5,9,1,0,1,0,0,0,0,0,0,1
4,4,143000,8,0,21,72,8.50,124999.5,9,1,0,1,0,0,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34794,35722,125000,6,1,33,431,3.50,32499.5,10,1,0,0,0,1,0,0,0,0,1
34795,35723,50000,7,1,46,217,22.51,22499.5,8,0,1,0,0,1,0,1,0,0,0
34796,35724,120000,7,1,17,245,8.50,134999.5,8,0,1,1,0,0,0,0,0,0,1
34797,35725,85000,8,1,57,291,17.51,274999.5,8,0,1,1,0,0,0,1,0,0,0
34798,35726,30000,11,0,44,61,25.51,224999.5,8,0,1,0,0,1,0,0,0,0,1

In [24]:
dummies_data.rename(columns={"Automatique":"automatic",
                             "Manuelle":"manuel",
                             "Diesel":"diesel",
                             "Electrique":"electric",
                             "Essence" : "gasoline",
                             "Hybride" :"hybrid",
                             "Dédouanée": "cleared",
                             "Importée neuve":"imported_new",
                             "Pas encore dédouanée":"not_yet_cleared",
                             "WW au Maroc":"ww_in_morocco"},
                             inplace = True)

In [29]:
dummies_data.to_csv(r"C:\Users\hp\avito_cars_data_LV.csv")

In [28]:
dummies_data.corr()["price"]

Unnamed: 0          -0.088248
price                1.000000
hp                   0.179717
is_first_use         0.317854
make                 0.084059
model                0.130865
age                 -0.631353
mileage             -0.129425
num_general_state    0.322985
automatic            0.597136
manuel              -0.597136
diesel               0.317368
electric             0.046171
gasoline            -0.342493
hybrid               0.088516
cleared              0.044563
imported_new         0.048030
not_yet_cleared      0.056720
ww_in_morocco       -0.075804
Name: price, dtype: float64